config/routes.rb
Rails.application.routes.draw do
  root 'animations#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do #            vvvvv-- index of animations for user
    resources :animations, only: [:index]
  end
  #                              vvvvv-- index of animations globally
  resources :animations, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  resources :animations, only: [] do
    resources :frames, only: [:index, :show]
    resources :comments, shallow: true
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :comments, only: [] do
    resources :votes, only: [:create, :update, :destroy]
  end

  resources :frames, only: [:destroy]
  # TODO: routes for...
  # - sharing single frames publicly (attribute "published" or similar on a frame)
  # - copying frames into 

  resources :tags
end

app/models/animation.rb
class Animation < ApplicationRecord
  extend FriendlyId

  PERMITTED_ATTRS = %i[
    name
    description
    movie
  ]

  belongs_to :user
  has_many :frames, dependent: :destroy
  has_many :votes, class_name: 'AnimationVote', dependent: :destroy
  has_many :comments
  has_many :animations_tags
  has_many :tags, through: :animations_tags

  mount_uploader :movie, MovieUploader
  serialize :movie, JSON

  friendly_id :name, use: :slugged

  validates :name, presence: true
  # validate :all_frames_are_equal_size

  # The error message for validates_associated will simply be "is invalid"; for
  # detailed errors check the child.
  validates_associated :tags
  validates_associated :frames

  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :frames

  def tags_attributes=(tags_attributes)
    self.tags = tags_attributes.map do |tag_attributes|
      Tag.where(name: tag_attributes[:name]).first_or_create(tag_attributes)
    end
  end

  def score
    # @score ||= votes.pluck(:value).sum
    votes.pluck(:value).sum
  end

  def duration
    # @duration ||= frames.pluck(:duration).sum
    frames.pluck(:duration).sum
  end

  def frame_at(position)
    frames.find_by(position: position)
  end

  private

  # def all_frames_are_equal_size
  #   binding.pry
  #   return if frames.empty?
  #   sizes = frames.pluck(:width, :height)
  #   widths = sizes.map(&:first)
  #   heights = sizes.map(&:second)
  #   unless widths.uniq.count == 1 && heights.uniq.count == 1
  #     errors.add(:frames, 'must be equal sizes')
  #   end
  # end
end

app/models/animation_vote.rb
class AnimationVote < ApplicationRecord
  belongs_to_votable :animation
end

app/models/animations_tag.rb
class AnimationsTag < ActiveRecord::Base
  belongs_to :animation
  belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  default_scope { defined?(friendly) ? friendly : all }

  # class << self
  #   def friendly
  #     defined()
  #   end
  # end
end

app/models/base_vote.rb
class BaseVote < ApplicationRecord
  self.abstract_class = true

  class << self
    # Must use this macro in child class.
    # e.g., belongs_to_votable :animation
    def belongs_to_votable(votable_model)
      @votable_model_name = votable_model.to_s.downcase.to_sym
      belongs_to @votable_model_name
    end

    def votable_model_name
      @votable_model_name
    end
  end

  MIN_VOTE_VALUE = 1
  MAX_VOTE_VALUE = 3

  belongs_to :user

  validates :value, presence: true, inclusion: { in: MIN_VOTE_VALUE..MAX_VOTE_VALUE }
  validate :no_duplicate_votes

  private

  def no_duplicate_votes
    max_prev_votes = persisted? ? 1 : 0
    prev_votes = votable_model.votes.where(user_id: user.id).count
    errors.add(:user, "cannot vote multiple times") if prev_votes > max_prev_votes
  end

  def votable_model
    send(self.class.votable_model_name)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :animation
  has_many :votes, class_name: 'CommentVote', dependent: :destroy

  validates :body, presence: true
end

app/models/comment_vote.rb
class CommentVote < BaseVote
  belongs_to_votable :comment
end

app/models/frame.rb
class Frame < ApplicationRecord
  PERMITTED_ATTRS = %i[
    color_map
    duration
    animation_id
    position
    width
    height
  ]

  belongs_to :animation

  serialize :color_map, JSON

  delegate :user, to: :animation

  # validates :position, presence: true, uniqueness: { scope: :animation_id }
  validates :duration, presence: true
  validates :color_map, presence: true
  # validate :frames_in_animation_are_equal_size

  # before_create :default_to_last_position!
  # before_create :default_to_white_color_map!

  default_scope { order(:animation_id, :position) }

  def previous_frames(inclusive: false)
    before_operator = inclusive ? '<=' : '<'
    animation.frames.where("position #{before_operator} ?", position)
  end

  def previous_frame
    previous_frames.last
  end

  def next_frames(inclusive: false)
    after_operator = inclusive ? '>=' : '>'
    animation.frames.where("position #{after_operator} ?", position)
  end

  def next_frame
    next_frames.first
  end

  def insert_at(new_position)
    return if new_position == position
    frames = animation.frames
    frames.where('position >= ?', new_position).update_all('position = position + 1')
    last_position = frames.last.position
    update(position: new_position > last_position ? last_position : new_position)
  end

  private

  # def default_to_last_position!
  #   self.position ||= animation.frames.last.position + 1
  # end

  # def default_to_white_color_map!
  #   self.color_map ||= height.times.map do |row|
  #     width.times.map do |column|
  #       '#FFFFFF'
  #     end
  #   end
  # end

  # def frames_in_animation_are_equal_size
  #   sizes = animation.frames.pluck(:width, :height)
  #   widths = sizes.map(&:first)
  #   heights = sizes.map(&:second)
  #   unless widths.uniq.count == 1 && heights.uniq.count == 1
  #     errors.add(:frames, 'must be equal sizes')
  #   end
  # end
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId

  PERMITTED_ATTRS = %i[
    name
    description
  ]

  has_many :animations_tags
  has_many :animations, through: :animations_tags

  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId

  PERMITTED_ATTRS = %i[
    handle
    password
    password_confirmation
    first_name
    last_name
    email
    phone
    bio
    signature
  ]

  has_many :animations

  has_secure_password

  friendly_id :handle, use: :slugged

  validates :handle, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, maximum: 100 }, confirmation: true

  enum role: {
    basic: 0,
    moderator: 1,
    admin: 2
  }

  # # NB: supplied by enum
  # scope :basic
  # scope :moderator
  # scope :admin

  def name
    "#{first_name.strip} #{last_name.strip}".strip
  end
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = authorize User.new
  end

  def edit; end

  def create
    @user = authorize User.new(user_params)
    if @user.save
      flash[:success] = "User '#{@user.handle}' created!"
      set_current_user(@user)
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User '#{@user.handle}' updated!"
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "User '#{@user.handle}' was deleted!"
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(*User::PERMITTED_ATTRS)
  end

  def set_user
    @user ||= authorize User.friendly.find(params[:id])
  end
end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title OdeTo16Color
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous")
    %script(src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous")
    %script(src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous")
    %script(src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous")

  %body
    %header
      %nav
        - if logged_in?
          = "logged in as #{current_user.handle}"
          = link_to 'new animation', new_animation_path
          = link_to 'profile', user_path(current_user)
          = link_to 'log out', logout_path, method: :delete
        - else
          = link_to 'log in', login_path
          = link_to 'sign up', signup_path
      .flash-area
        - flash.keys.each do |flash_type|
          .flash-message{ class: flash_type }
            = flash[flash_type]

    %main.container
      = yield

    %footer
      .github-link= link_to 'source code', 'https://github.com/kjleitz/ode-to-16-color'
      .license-desc license: MIT

    %script(src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous")
    %script(src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous")
    %script(src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous")